language:
  - node_js

node_js:
  - 7
  - 6
  - 4

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - npm update
  - npm prune

script:
  - npm test
  - npm run cover

after_success:
  - test $TRAVIS_NODE_VERSION = 6 && bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
  on:
    branch: master
    node: 6
