language:
  - node_js

node_js:
  - 8
  - 6
  - 4

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

install:
  - npm update
  - npm prune

script:
  - npm test
  - npm run cover

after_success:
  - test $TRAVIS_NODE_VERSION = 8 && bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: publish
      node_js: 8
      install: npm install
      script: npm run release
