language:
  - node_js

node_js:
  - 'node'
  - '6'
  - '4'

script:
  - npm test
  - npm run cover


after_success:
  - test $TRAVIS_NODE_VERSION = 6 && bash <(curl -s https://codecov.io/bash)

deploy:
  on:
    branch: master
    node: 6
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
